[project]
name = "airis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "esptool>=5.1.0",
    "machine>=0.0.1",
    "mpremote>=1.26.1",
]
